[build]
  publish = "project/dist"
  command = "cd project && npm run build:netlify"

[functions]
  directory = "project/netlify/functions"
  node_bundler = "esbuild"
  included_files = ["project/emailProcessor.js", "project/emailPollingService.js", "project/aiService.js", "project/graphService.js"]

[[redirects]]
  from = "/api/polling-user"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max_old_space_size=4096"
