[build]
  command = "npm run build:netlify"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max_old_space_size=4096"
