-- Migration: Initial Schema Baseline
-- Created: 2026-04-08
-- Purpose: Schema base para Supabase Branching (staging)
-- Seguro em producao: usa CREATE TABLE IF NOT EXISTS

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- TIPOS CUSTOMIZADOS
DO $$ BEGIN
  CREATE TYPE term_type AS ENUM ('application', 'affiliate', 'general');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE identity_photo_status AS ENUM ('pending', 'approved', 'rejected');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- TABELAS
CREATE TABLE IF NOT EXISTS admin_logs (id uuid NOT NULL, admin_user_id uuid, action text NOT NULL, target_type text NOT NULL, target_id uuid, details jsonb, ip_address inet, user_agent text, created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS admin_notifications (id uuid NOT NULL, user_id uuid NOT NULL, title text NOT NULL, message text NOT NULL, link text, type text, metadata jsonb, is_read boolean, read_at timestamp with time zone, created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS admin_student_chat_notifications (id uuid NOT NULL, conversation_id uuid NOT NULL, message_id uuid NOT NULL, recipient_id uuid NOT NULL, sender_id uuid NOT NULL, title text NOT NULL, message text NOT NULL, notification_type text NOT NULL, is_read boolean NOT NULL, email_sent boolean, email_sent_at timestamp with time zone, created_at timestamp with time zone NOT NULL, read_at timestamp with time zone, metadata jsonb);
CREATE TABLE IF NOT EXISTS admin_student_conversations (id uuid NOT NULL, admin_id uuid, student_id uuid, created_at timestamp with time zone, updated_at timestamp with time zone, last_message_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS admin_student_message_attachments (id uuid NOT NULL, message_id uuid, file_url text NOT NULL, file_name text, file_size integer, mime_type text, created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS admin_student_messages (id uuid NOT NULL, conversation_id uuid, sender_id uuid, recipient_id uuid, message text NOT NULL, created_at timestamp with time zone, updated_at timestamp with time zone, read_at timestamp with time zone, edited_at timestamp with time zone, is_deleted boolean, is_system_message boolean NOT NULL);
CREATE TABLE IF NOT EXISTS affiliate_admin_notifications (id uuid NOT NULL, affiliate_admin_id uuid NOT NULL, title text NOT NULL, message text NOT NULL, link text, read_at timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone, notification_type text, metadata jsonb);
CREATE TABLE IF NOT EXISTS affiliate_admins (id uuid NOT NULL, user_id uuid, created_by_admin_id uuid, is_active boolean, created_at timestamp with time zone, updated_at timestamp with time zone, system_type text);
CREATE TABLE IF NOT EXISTS affiliate_clicks (id uuid NOT NULL, user_id uuid NOT NULL, affiliate_code_id uuid NOT NULL, clicked_at timestamp with time zone, ip_address inet, user_agent text, referrer text, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS affiliate_codes (id uuid NOT NULL, user_id uuid, code text NOT NULL, is_active boolean, total_referrals integer, total_earnings numeric(10,2), created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS affiliate_payment_requests (id uuid NOT NULL, referrer_user_id uuid NOT NULL, amount_usd numeric(10,2) NOT NULL, payout_method text NOT NULL, payout_details jsonb, status text NOT NULL, admin_notes text, approved_by uuid, approved_at timestamp with time zone, paid_by uuid, paid_at timestamp with time zone, payment_reference text, created_at timestamp with time zone, rejected_by uuid, rejected_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS affiliate_referrals (id uuid NOT NULL, referrer_id uuid, referred_id uuid, affiliate_code text NOT NULL, payment_amount numeric(10,2), credits_earned numeric(10,2), status text, payment_session_id text, created_at timestamp with time zone, completed_at timestamp with time zone, referred_student_status text, selection_process_paid_at timestamp with time zone, scholarship_fee_paid_at timestamp with time zone, i20_paid_at timestamp with time zone, last_status_update timestamp with time zone, application_fee_paid_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS affiliate_shares (id uuid NOT NULL, user_id uuid NOT NULL, affiliate_code_id uuid NOT NULL, platform text NOT NULL, shared_at timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS affiliate_terms (id uuid NOT NULL, title text NOT NULL, content text NOT NULL, status boolean, version integer, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL, is_active boolean);
CREATE TABLE IF NOT EXISTS ai_agent_knowledge_documents (id uuid NOT NULL, ai_configuration_id uuid, document_name text NOT NULL, file_url text NOT NULL, file_size integer, mime_type text, uploaded_by_user_id uuid, created_at timestamp with time zone, updated_at timestamp with time zone, transcription text, transcription_status text, transcription_processed_at timestamp with time zone, webhook_result jsonb);
CREATE TABLE IF NOT EXISTS ai_configurations (id uuid NOT NULL, user_id uuid NOT NULL, university_id uuid, ai_name text, company_name text, agent_type text, personality text, has_tested boolean, created_at timestamp with time zone, updated_at timestamp with time zone, sector text, is_template boolean, final_prompt text, webhook_status text, webhook_result jsonb, webhook_processed_at timestamp with time zone, embed_config jsonb, custom_prompt text, is_active boolean);
CREATE TABLE IF NOT EXISTS ai_email_agent_knowledge_documents (id uuid NOT NULL, ai_email_agent_id uuid NOT NULL, document_name text NOT NULL, file_url text NOT NULL, file_size bigint NOT NULL, mime_type text NOT NULL, uploaded_by_user_id uuid NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL, transcription text, transcription_status text, transcription_processed_at timestamp with time zone, webhook_result jsonb);
CREATE TABLE IF NOT EXISTS ai_email_agents (id uuid NOT NULL, email_configuration_id uuid NOT NULL, user_id uuid NOT NULL, ai_name text NOT NULL, agent_type text, personality text, custom_prompt text, has_documents boolean NOT NULL, is_active boolean NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL, final_prompt text, webhook_status text, webhook_result jsonb, webhook_processed_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS ai_email_conversations (id uuid NOT NULL, message_id text NOT NULL, conversation_id text, university_id uuid NOT NULL, sender_email text NOT NULL, received_at timestamp with time zone, email_subject text, email_body text, email_html_body text, ai_response_body text, ai_response_html text, responded_at timestamp with time zone, status text, error_details text, processing_time_ms integer, confidence_score numeric(3,2), thread_id text, attachments jsonb, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS ai_email_metrics (id uuid NOT NULL, conversation_id uuid, processing_time_ms integer NOT NULL, ai_service_provider text NOT NULL, ai_model_used text NOT NULL, prompt_tokens integer, completion_tokens integer, response_confidence_score numeric(3,2), cost_usd numeric(10,4), created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS ai_usage_limits (id uuid NOT NULL, university_id uuid NOT NULL, session_id text NOT NULL, prompts_used integer, max_prompts integer, last_prompt_at timestamp with time zone, reset_at timestamp with time zone NOT NULL, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS application_message_attachments (id uuid NOT NULL, message_id uuid NOT NULL, file_url text NOT NULL, file_name text, uploaded_at timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS application_messages (id uuid NOT NULL, application_id uuid NOT NULL, sender_id uuid NOT NULL, recipient_id uuid NOT NULL, message text NOT NULL, sent_at timestamp with time zone NOT NULL, is_read boolean NOT NULL, read_at timestamp with time zone, email_sent timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS application_terms (id uuid NOT NULL, title text NOT NULL, content text NOT NULL, term_type term_type NOT NULL, version integer, is_active boolean, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS chatwoot_accounts (id uuid NOT NULL, user_id uuid, chatwoot_user_name text, chatwoot_email text, chatwoot_password text, chatwoot_access_token text, chatwoot_instance_name text, chatwoot_user_id text, chatwoot_account_id text, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS comprehensive_term_acceptance (id uuid NOT NULL, user_id uuid NOT NULL, term_id uuid NOT NULL, term_type term_type NOT NULL, accepted_at timestamp with time zone NOT NULL, ip_address inet, user_agent text, created_at timestamp with time zone NOT NULL, identity_photo_path text, identity_photo_name text, identity_photo_status identity_photo_status, identity_photo_rejection_reason text, identity_photo_reviewed_at timestamp with time zone, identity_photo_reviewed_by uuid);
CREATE TABLE IF NOT EXISTS custom_agent_types (id uuid NOT NULL, user_id uuid, university_id uuid, agent_type_name text NOT NULL, created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS document_request_uploads (id uuid NOT NULL, document_request_id uuid NOT NULL, uploaded_by uuid NOT NULL, file_url text NOT NULL, uploaded_at timestamp with time zone NOT NULL, status text NOT NULL, reviewed_by uuid, reviewed_at timestamp with time zone, review_notes text, rejection_reason text);
CREATE TABLE IF NOT EXISTS document_requests (id uuid NOT NULL, created_by uuid NOT NULL, scholarship_application_id uuid, title text NOT NULL, description text, due_date date, attachment_url text, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL, is_bulk boolean NOT NULL, status text NOT NULL, university_id uuid, is_global boolean, applicable_student_types text[]);
CREATE TABLE IF NOT EXISTS eb3_payments (id uuid NOT NULL, session_id text NOT NULL, payment_intent_id text, amount integer NOT NULL, currency text, status text NOT NULL, customer_email text, customer_name text, created_at timestamp with time zone, updated_at timestamp with time zone, customer_phone text, user_id uuid, user_profile_id uuid, stripe_customer_id text, payment_method text, metadata jsonb);
CREATE TABLE IF NOT EXISTS email_ai_bindings (id uuid NOT NULL, email_configuration_id uuid, ai_configuration_id uuid, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS email_attachments (id uuid NOT NULL, email_id uuid, email_type character varying(20) NOT NULL, filename character varying(255) NOT NULL, content_type character varying(100), size_bytes integer, storage_path text, created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS email_configurations (id uuid NOT NULL, user_id uuid NOT NULL, name character varying(255) NOT NULL, email_address character varying(255) NOT NULL, smtp_host character varying(255), smtp_port integer NOT NULL, smtp_secure boolean, smtp_auth_user character varying(255), smtp_auth_pass text, imap_host character varying(255), imap_port integer NOT NULL, imap_secure boolean, imap_auth_user character varying(255), imap_auth_pass text, is_active boolean, last_sync_at timestamp with time zone, sync_enabled boolean, sync_interval_minutes integer, created_at timestamp with time zone, updated_at timestamp with time zone, provider_type character varying(20) NOT NULL, oauth_access_token text, oauth_refresh_token text, oauth_token_expires_at timestamp with time zone, microsoft_account_id character varying(255), ai_processing boolean);
CREATE TABLE IF NOT EXISTS email_connections (id uuid NOT NULL, user_id uuid, provider character varying(20) NOT NULL, access_token text NOT NULL, refresh_token text, expires_at timestamp with time zone, email character varying(255), scopes text, created_at timestamp with time zone, updated_at timestamp with time zone, last_history_id text);
CREATE TABLE IF NOT EXISTS email_knowledge_documents (id uuid NOT NULL, university_id uuid NOT NULL, document_name text NOT NULL, file_url text NOT NULL, file_size integer NOT NULL, mime_type text NOT NULL, uploaded_by_user_id uuid, transcription text, transcription_status text, transcription_processed_at timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone, agent_id uuid);
CREATE TABLE IF NOT EXISTS email_processing_configs (id uuid NOT NULL, user_id uuid NOT NULL, access_token text NOT NULL, refresh_token text NOT NULL, last_processed_email_id text, is_active boolean, created_at timestamp with time zone, updated_at timestamp with time zone, token_expires_at timestamp with time zone, total_processed integer, total_replied integer, last_processing_date timestamp with time zone, email_address text);
CREATE TABLE IF NOT EXISTS email_processing_initialized (id uuid NOT NULL, user_id uuid NOT NULL, connection_email text NOT NULL, initialized_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS email_queue (id uuid NOT NULL, user_id uuid NOT NULL, email_data jsonb NOT NULL, status text, priority integer, created_at timestamp with time zone, started_at timestamp with time zone, completed_at timestamp with time zone, error_message text, retry_count integer, next_retry_at timestamp with time zone, email_configuration_id uuid);
CREATE TABLE IF NOT EXISTS email_rate_limits (id uuid NOT NULL, user_id uuid NOT NULL, hourly_count integer, hourly_reset bigint NOT NULL, daily_count integer, daily_reset bigint NOT NULL, last_email_sent bigint, created_at timestamp with time zone, updated_at timestamp with time zone, burst_count integer, burst_reset bigint);
CREATE TABLE IF NOT EXISTS inbox_ai_settings (id uuid NOT NULL, university_id uuid NOT NULL, knowledge_base_enabled boolean, max_documents integer, allowed_file_types text[], auto_process_enabled boolean, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS inbox_email_prompts (id uuid NOT NULL, university_id uuid NOT NULL, prompt text, created_by_user_id uuid, updated_by_user_id uuid, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS inbox_knowledge_documents (id uuid NOT NULL, university_id uuid NOT NULL, document_name text NOT NULL, file_url text NOT NULL, file_size integer, mime_type text, transcription text, transcription_status text, uploaded_by_user_id uuid, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS individual_fee_payments (id uuid NOT NULL, user_id uuid NOT NULL, fee_type text NOT NULL, amount numeric(10,2) NOT NULL, payment_date timestamp with time zone NOT NULL, payment_method text NOT NULL, payment_intent_id text, stripe_charge_id text, zelle_payment_id uuid, created_at timestamp with time zone, updated_at timestamp with time zone, gross_amount_usd numeric(10,2), fee_amount_usd numeric(10,2), parcelow_order_id text, parcelow_status text, parcelow_checkout_url text, parcelow_reference text, source text NOT NULL DEFAULT 'matriculausa');
CREATE TABLE IF NOT EXISTS legal_documents (id uuid NOT NULL, user_id uuid NOT NULL, document_type text NOT NULL, related_id uuid NOT NULL, storage_path text NOT NULL, filename text NOT NULL, email_sent boolean, email_sent_at timestamp with time zone, email_error text, metadata jsonb, created_at timestamp with time zone, updated_at timestamp with time zone, source text NOT NULL DEFAULT 'matriculausa');
CREATE TABLE IF NOT EXISTS matriculacoin_credits (id uuid NOT NULL, user_id uuid, balance numeric(10,2), total_earned numeric(10,2), total_spent numeric(10,2), created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS matriculacoin_transactions (id uuid NOT NULL, user_id uuid, type text NOT NULL, amount numeric(10,2) NOT NULL, description text, reference_id uuid, reference_type text, balance_after numeric(10,2), created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS microsoft_ai_agent_knowledge_documents (id uuid NOT NULL, microsoft_ai_agent_id uuid, document_name text NOT NULL, document_url text NOT NULL, document_type text, file_size integer, transcription text, transcription_status text, transcription_processed_at timestamp with time zone, webhook_result jsonb, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS microsoft_ai_agents (id uuid NOT NULL, user_id uuid NOT NULL, university_id uuid NOT NULL, email_configuration_id uuid, ai_name text NOT NULL, company_name text NOT NULL, agent_type text, personality text NOT NULL, sector text, custom_prompt text, final_prompt text, webhook_status text, webhook_result jsonb, webhook_processed_at timestamp with time zone, is_active boolean, created_at timestamp with time zone, updated_at timestamp with time zone, knowledge_documents jsonb);
CREATE TABLE IF NOT EXISTS newsletter_campaigns (id uuid NOT NULL, campaign_key text NOT NULL, name text NOT NULL, description text, email_subject_template text NOT NULL, email_body_template text NOT NULL, trigger_conditions jsonb, cooldown_days integer, is_active boolean, created_at timestamp with time zone, updated_at timestamp with time zone, send_once boolean);
CREATE TABLE IF NOT EXISTS newsletter_sent_emails (id uuid NOT NULL, user_id uuid NOT NULL, campaign_id uuid NOT NULL, email_address text NOT NULL, subject text NOT NULL, sent_at timestamp with time zone, status text, metadata jsonb, created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS newsletter_user_preferences (id uuid NOT NULL, user_id uuid NOT NULL, email_opt_out boolean, opt_out_reason text, opt_out_at timestamp with time zone, last_email_sent_at timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone, email_opt_in boolean, opt_in_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS payment_transfers (id uuid NOT NULL, university_id uuid NOT NULL, payment_id uuid, transfer_amount integer NOT NULL, transfer_status text NOT NULL, transfer_method text NOT NULL, admin_notes text, processed_by uuid, processed_at timestamp with time zone, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS payments (id uuid NOT NULL, student_id uuid NOT NULL, university_id uuid, payment_type text NOT NULL, amount_charged numeric NOT NULL, currency text NOT NULL, status text NOT NULL, stripe_charge_id text, stripe_payment_intent_id text NOT NULL, stripe_transfer_id text, platform_fee_amount numeric, amount_transferred_to_recipient numeric, due_date date, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS payout_invoices (id uuid NOT NULL, payout_request_id uuid NOT NULL, invoice_number text NOT NULL, issued_at timestamp with time zone, due_at timestamp with time zone, total_usd numeric(12,2) NOT NULL, status text NOT NULL, created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS pre_registration_leads (id uuid NOT NULL, full_name text, email text NOT NULL, phone text, source_page text, status text, created_at timestamp with time zone, updated_at timestamp with time zone, session_id uuid);
CREATE TABLE IF NOT EXISTS processed_emails (id uuid NOT NULL, gmail_message_id text NOT NULL, user_id uuid NOT NULL, connection_email text NOT NULL, sent_at timestamp with time zone, status text NOT NULL, payload jsonb, error_message text, retry_count integer, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS processed_microsoft_emails (id uuid NOT NULL, microsoft_message_id text NOT NULL, user_id uuid NOT NULL, connection_email text NOT NULL, subject text, from_email text, status text NOT NULL, analysis jsonb, response_text text, processed_at timestamp with time zone, error_message text, created_at timestamp with time zone, updated_at timestamp with time zone, original_email_content text);
CREATE TABLE IF NOT EXISTS processed_notifications (id bigint NOT NULL, history_id bigint NOT NULL, email_address text NOT NULL, processed_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS promotional_coupon_usage (id uuid NOT NULL, user_id uuid NOT NULL, coupon_id uuid, coupon_code text NOT NULL, fee_type text NOT NULL, original_amount numeric(10,2) NOT NULL, discount_amount numeric(10,2) NOT NULL, final_amount numeric(10,2) NOT NULL, payment_session_id text, stripe_coupon_id text, status text, applied_at timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone, payment_id text, payment_method text, stripe_session_id text, zelle_payment_id uuid, individual_fee_payment_id uuid, metadata jsonb, used_at timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS promotional_coupons (id uuid NOT NULL, code text NOT NULL, name text NOT NULL, description text, discount_type text NOT NULL, discount_value numeric(10,2) NOT NULL, is_active boolean, valid_from timestamp with time zone, valid_until timestamp with time zone, max_uses integer, current_uses integer, max_uses_per_user integer, min_purchase_amount numeric(10,2), excluded_fee_types text[], stripe_coupon_id text, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS received_emails (id uuid NOT NULL, email_config_id uuid NOT NULL, message_id character varying(500) NOT NULL, subject text, from_address text NOT NULL, from_name text, to_addresses text[], cc_addresses text[], bcc_addresses text[], reply_to text, text_content text, html_content text, is_read boolean, is_flagged boolean, is_deleted boolean, received_date timestamp with time zone NOT NULL, created_at timestamp with time zone, updated_at timestamp with time zone, is_archived boolean, is_spam boolean);
CREATE TABLE IF NOT EXISTS reward_redemptions (id uuid NOT NULL, user_id uuid, reward_id uuid, cost_paid integer NOT NULL, status text, redeemed_at timestamp with time zone, used_at timestamp with time zone, expires_at timestamp with time zone, metadata jsonb);
CREATE TABLE IF NOT EXISTS rewards (id uuid NOT NULL, name text NOT NULL, description text, cost integer NOT NULL, type text NOT NULL, value numeric(10,2) NOT NULL, duration integer, is_active boolean, image_url text, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS scholarship_applications (id uuid NOT NULL, student_id uuid, scholarship_id uuid, status text, applied_at timestamp with time zone, reviewed_at timestamp with time zone, reviewed_by uuid, notes text, documents jsonb, created_at timestamp with time zone, updated_at timestamp with time zone, student_process_type text, paid_at timestamp with time zone, payment_status text, is_application_fee_paid boolean, is_scholarship_fee_paid boolean, acceptance_letter_url text, acceptance_letter_signed_url text, acceptance_letter_status text, acceptance_letter_sent_at timestamp with time zone, acceptance_letter_signed_at timestamp with time zone, acceptance_letter_approved_at timestamp with time zone, application_fee_notification_sent boolean, stripe_transfer_status text, stripe_transfer_id text, stripe_transfer_amount integer, stripe_transfer_date timestamp with time zone, seller_id uuid, affiliate_admin_id uuid, referred_at timestamp with time zone, application_fee_payment_method text, scholarship_fee_payment_method text, transfer_form_url text, transfer_form_status text, transfer_form_sent_at timestamp with time zone, source text NOT NULL DEFAULT 'matriculausa');
CREATE TABLE IF NOT EXISTS scholarship_favorites (id uuid NOT NULL, user_id uuid NOT NULL, scholarship_id uuid NOT NULL, created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS scholarship_fee_payments (id uuid NOT NULL, user_id uuid NOT NULL, scholarships_ids text NOT NULL, payment_intent_id text NOT NULL, created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS scholarship_packages (id uuid NOT NULL, name text NOT NULL, description text, package_number integer NOT NULL, selection_process_fee numeric(10,2) NOT NULL, i20_control_fee numeric(10,2) NOT NULL, scholarship_fee numeric(10,2) NOT NULL, total_paid numeric(10,2) NOT NULL, scholarship_amount numeric(10,2) NOT NULL, is_active boolean, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS scholarships (id uuid NOT NULL, title text NOT NULL, description text, amount numeric(12,2) NOT NULL, deadline date NOT NULL, requirements text[], field_of_study text, level text, eligibility text[], benefits text[], is_exclusive boolean, is_active boolean, university_id uuid, created_at timestamp with time zone, updated_at timestamp with time zone, needcpt boolean, visaassistance text, scholarshipvalue numeric, image_url text, original_value_per_credit numeric(12,2), original_annual_value numeric(12,2), scholarship_type text, annual_value_with_scholarship numeric(12,2), work_permissions text[], delivery_mode text, is_highlighted boolean, featured_order integer, application_fee_amount numeric(12,2), is_stripe_connect_enabled boolean, university_stripe_account_id text, scholarship_fee_amount integer, internal_fees jsonb, placement_fee_amount numeric, min_gpa numeric, min_english_proficiency text, is_test boolean);
CREATE TABLE IF NOT EXISTS seller_fee_payments (id uuid NOT NULL, seller_referral_id uuid, payment_id uuid, student_id uuid, seller_id uuid, fee_type text NOT NULL, amount_paid numeric(10,2) NOT NULL, seller_commission numeric(10,2) NOT NULL, payment_date timestamp with time zone, status text, notes text, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS seller_notifications (id uuid NOT NULL, seller_id uuid NOT NULL, title text NOT NULL, message text NOT NULL, link text, read_at timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone, notification_type text, metadata jsonb);
CREATE TABLE IF NOT EXISTS seller_referrals (id uuid NOT NULL, seller_id uuid, student_id uuid, seller_referral_code text NOT NULL, referral_date timestamp with time zone, student_status text, commission_earned numeric(10,2), notes text, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS seller_registration_codes (id uuid NOT NULL, admin_id uuid, code text NOT NULL, is_active boolean, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS seller_registration_history (id uuid NOT NULL, user_id uuid, admin_id uuid, registration_code text NOT NULL, status text NOT NULL, action_taken_at timestamp with time zone, notes text, created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS seller_registrations (id uuid NOT NULL, admin_id uuid, registration_code text NOT NULL, email text NOT NULL, full_name text NOT NULL, phone text, status text, created_at timestamp with time zone, approved_at timestamp with time zone, approved_by uuid, updated_at timestamp with time zone, user_id uuid);
CREATE TABLE IF NOT EXISTS sellers (id uuid NOT NULL, affiliate_admin_id uuid, name text NOT NULL, email text NOT NULL, phone text, territory text, referral_code text NOT NULL, is_active boolean, notes text, created_at timestamp with time zone, updated_at timestamp with time zone, user_id uuid, commission_rate numeric(5,4));
CREATE TABLE IF NOT EXISTS sent_emails (id uuid NOT NULL, email_config_id uuid NOT NULL, subject text, to_addresses text[] NOT NULL, cc_addresses text[], bcc_addresses text[], reply_to text, text_content text, html_content text, status character varying(50), error_message text, sent_at timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS state_mapping (id integer NOT NULL, abbreviation character varying(2) NOT NULL, full_name character varying(50) NOT NULL, created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS stripe_connect_states (id uuid NOT NULL, university_id uuid NOT NULL, state text NOT NULL, expires_at timestamp with time zone NOT NULL, created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS stripe_connect_transfers (id uuid NOT NULL, transfer_id text, session_id text NOT NULL, payment_intent_id text NOT NULL, application_id uuid, user_id uuid, university_id uuid NOT NULL, amount integer NOT NULL, status text NOT NULL, destination_account text NOT NULL, error_message text, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS student_action_logs (id uuid NOT NULL, student_id uuid NOT NULL, action_type text NOT NULL, action_description text NOT NULL, performed_by uuid NOT NULL, performed_by_type text NOT NULL, performed_by_name text, performed_by_email text, metadata jsonb, created_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS student_documents (id uuid NOT NULL, user_id uuid, type text NOT NULL, file_url text NOT NULL, status text, uploaded_at timestamp with time zone, approved_at timestamp with time zone, source text NOT NULL DEFAULT 'matriculausa');
CREATE TABLE IF NOT EXISTS student_notifications (id uuid NOT NULL, student_id uuid NOT NULL, title text NOT NULL, message text NOT NULL, link text, created_at timestamp with time zone NOT NULL, read_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS submissions (id uuid NOT NULL, user_id uuid, name text, email text, whatsapp text, profile_type text, answers jsonb, extra_answers jsonb, score integer, total integer, percentage integer, passed boolean, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS system_settings (key text NOT NULL, value text NOT NULL, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS transfer_form_uploads (id uuid NOT NULL, application_id uuid NOT NULL, file_url text NOT NULL, uploaded_by uuid NOT NULL, status text NOT NULL, review_notes text, rejection_reason text, uploaded_at timestamp with time zone NOT NULL, reviewed_at timestamp with time zone, reviewed_by uuid);
CREATE TABLE IF NOT EXISTS translation_orders (id uuid NOT NULL, user_id uuid NOT NULL, document_type text NOT NULL, source_language text NOT NULL, target_language text NOT NULL, document_url text NOT NULL, original_document_type text NOT NULL, page_count integer NOT NULL, price_per_page numeric NOT NULL, total_price numeric NOT NULL, status text NOT NULL, payment_method text, payment_reference text, stripe_session_id text, translated_document_url text, notes text, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL, tfoe_verification_code uuid, tfoe_document_id uuid, tfoe_status text, tfoe_submitted_at timestamp with time zone, is_bank_statement boolean, is_authenticated boolean, original_filename text, client_name text);
CREATE TABLE IF NOT EXISTS tuition_discounts (id uuid NOT NULL, name text NOT NULL, description text, cost_coins integer NOT NULL, discount_amount numeric(10,2) NOT NULL, is_active boolean, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS tuition_redemptions (id uuid NOT NULL, user_id uuid, university_id uuid, discount_id uuid, cost_coins_paid integer NOT NULL, discount_amount numeric(10,2) NOT NULL, status text, redeemed_at timestamp with time zone, confirmed_at timestamp with time zone, expires_at timestamp with time zone, metadata jsonb);
CREATE TABLE IF NOT EXISTS universities (id uuid NOT NULL, name text NOT NULL, description text, location text, website text, logo_url text, programs text[], address jsonb, contact jsonb, user_id uuid, is_approved boolean, profile_completed boolean, terms_accepted boolean, created_at timestamp with time zone, updated_at timestamp with time zone, slug text, image_url text, established_year integer, student_count integer, type text, campus_size text, is_featured boolean, featured_order integer, participates_in_matricula_rewards boolean, matricula_rewards_opted_in_at timestamp with time zone, matricula_rewards_opt_in_notes text, state text, banner_url text, default_payment_method text, payment_method_details jsonb, payment_instructions text, payment_contact_email text, payment_contact_phone text, university_fees_page_url text);
CREATE TABLE IF NOT EXISTS university_ai_settings (id uuid NOT NULL, university_id uuid NOT NULL, is_ai_enabled boolean, custom_instructions text, response_tone text, forward_to_human_triggers text[], ai_service_provider text, ai_model text, max_response_length integer, confidence_threshold numeric(3,2), created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS university_balance_accounts (id uuid NOT NULL, university_id uuid NOT NULL, total_revenue numeric(12,2), total_reserved numeric(12,2), total_paid_out numeric(12,2), available_balance numeric(12,2), last_updated timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS university_fee_configurations (id uuid NOT NULL, university_id uuid, default_application_fee numeric(12,2), platform_fee_percentage numeric(5,2), stripe_connect_account_id text, is_stripe_connect_enabled boolean, created_at timestamp with time zone, updated_at timestamp with time zone, stripe_account_name text, stripe_charges_enabled boolean, stripe_payouts_enabled boolean, stripe_requirements_completed boolean, stripe_access_token text, stripe_refresh_token text, stripe_token_expires_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS university_notifications (id uuid NOT NULL, university_id uuid NOT NULL, title text NOT NULL, message text NOT NULL, type text NOT NULL, metadata jsonb, link text, read_at timestamp with time zone, created_at timestamp with time zone NOT NULL, idempotency_key text);
CREATE TABLE IF NOT EXISTS university_payout_requests (id uuid NOT NULL, university_id uuid NOT NULL, requested_by uuid, amount_coins integer NOT NULL, amount_usd numeric(12,2) NOT NULL, payout_method text NOT NULL, payout_details_preview jsonb, payout_details_encrypted bytea, status text NOT NULL, admin_notes text, approved_by uuid, approved_at timestamp with time zone, paid_by uuid, paid_at timestamp with time zone, cancelled_by uuid, cancelled_at timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone, request_type text);
CREATE TABLE IF NOT EXISTS university_rewards_account (id uuid NOT NULL, university_id uuid, total_received_coins integer, total_discounts_sent integer, total_discount_amount numeric(10,2), balance_coins integer, created_at timestamp with time zone, updated_at timestamp with time zone, last_payout_at timestamp with time zone, total_payouts integer);
CREATE TABLE IF NOT EXISTS used_referral_codes (id uuid NOT NULL, user_id uuid, affiliate_code text NOT NULL, referrer_id uuid, discount_amount numeric(10,2), stripe_coupon_id text, payment_session_id text, status text, applied_at timestamp with time zone, expires_at timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone, email text);
CREATE TABLE IF NOT EXISTS user_cart (id uuid NOT NULL, user_id uuid NOT NULL, scholarship_id uuid NOT NULL, created_at timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS user_fee_overrides (id integer NOT NULL, user_id uuid NOT NULL, selection_process_fee numeric(10,2), application_fee numeric(10,2), scholarship_fee numeric(10,2), i20_control_fee numeric(10,2), created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL, placement_fee numeric(10,2), ds160_package_fee numeric, i539_cos_package_fee numeric);
CREATE TABLE IF NOT EXISTS user_profiles (id uuid NOT NULL, user_id uuid, full_name text, phone text, country text, field_of_interest text, academic_level text, gpa numeric(3,2), english_proficiency text, status text, last_active timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone, is_application_fee_paid boolean, stripe_customer_id text, stripe_payment_intent_id text, has_paid_selection_process_fee boolean NOT NULL DEFAULT false, is_scholarship_fee_paid boolean, documents_status text, documents_uploaded boolean, selected_scholarship_id uuid, has_paid_college_enrollment_fee boolean, email text, has_paid_i20_control_fee boolean NOT NULL DEFAULT false, i20_control_fee_due_date date, i20_control_fee_payment_intent_id text, documents jsonb, last_payment_date timestamp with time zone, university_id uuid, student_id uuid, role text, avatar_url text, referral_code_used text, referred_by_seller_id uuid, affiliate_admin_id uuid, referred_at timestamp with time zone, total_paid numeric, seller_referral_code text, affiliate_code text, seller_registration_code text, scholarship_package_id uuid, dependents integer, desired_scholarship_range numeric, admin_notes text, selection_process_fee_payment_method text, i20_control_fee_payment_method text, system_type text, onboarding_completed boolean, company_name text, website text, territory text, notifications jsonb, cpf_document text, selection_process_paid_at timestamp with time zone, application_fee_paid_at timestamp with time zone, scholarship_fee_paid_at timestamp with time zone, i20_paid_at timestamp with time zone, selection_survey_passed boolean, placement_fee_flow boolean, is_placement_fee_paid boolean, placement_fee_payment_method text, onboarding_current_step text, placement_fee_paid_at timestamp with time zone, has_paid_ds160_package boolean NOT NULL DEFAULT false, has_paid_i539_cos_package boolean NOT NULL DEFAULT false, student_process_type text, ds160_package_payment_method text, i539_cos_package_payment_method text, selected_application_id uuid, visa_transfer_active boolean, has_paid_reinstatement_package boolean, reinstatement_package_payment_method text, is_archived boolean, assigned_to_admin_id uuid, is_restricted_admin boolean, placement_fee_pending_balance numeric(10,2), placement_fee_due_date timestamp with time zone, placement_fee_installment_number smallint, placement_fee_installment_enabled boolean, source text NOT NULL DEFAULT 'matriculausa', migma_seller_id text, migma_agent_id text, no_referral_discount boolean);
CREATE TABLE IF NOT EXISTS user_terms_acceptance (id uuid NOT NULL, user_id uuid NOT NULL, term_id uuid NOT NULL, accepted_at timestamp with time zone NOT NULL, created_at timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS utm_attributions (id uuid NOT NULL, user_id uuid, email text, utm_source text, utm_medium text, utm_campaign text, utm_term text, utm_content text, landing_page text, last_touch_page text, referrer text, captured_at timestamp with time zone, created_at timestamp with time zone, client_name text, client_email text);
CREATE TABLE IF NOT EXISTS whatsapp_connections (id uuid NOT NULL, university_id uuid, phone_number text, connection_status text NOT NULL, connected_at timestamp with time zone, disconnected_at timestamp with time zone, instance_name text NOT NULL, created_at timestamp with time zone, updated_at timestamp with time zone, ai_configuration_id uuid, evolution_instance_id text, user_id uuid NOT NULL, final_prompt text);
CREATE TABLE IF NOT EXISTS worker_locks (id uuid NOT NULL, lock_key text NOT NULL, is_active boolean NOT NULL, created_at timestamp with time zone NOT NULL, expires_at timestamp with time zone, metadata jsonb);
CREATE TABLE IF NOT EXISTS zelle_payments (id uuid NOT NULL, user_id uuid, fee_type text, amount numeric(10,2) NOT NULL, recipient_name text, recipient_email text, confirmation_code text, payment_date date, payment_amount text, screenshot_url text, status text, scholarships_ids uuid[], created_at timestamp with time zone, updated_at timestamp with time zone, fee_type_global text, student_profile_id uuid, admin_approved_at timestamp with time zone, admin_approved_by uuid, admin_notes text, metadata jsonb, currency text, verified_at timestamp with time zone);
